# Generated by Django 4.2.5 on 2023-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0004_library_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='categories',
            field=models.ManyToManyField(to='kitaplar.category'),
        ),
    ]
