# Generated by Django 4.2.5 on 2023-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0005_library_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
