# Generated by Django 4.2.5 on 2023-11-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0007_authorr_publisherr_remove_library_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='author',
        ),
        migrations.RemoveField(
            model_name='library',
            name='publisher',
        ),
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitaplar.authorr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='publisher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='kitaplar.publisherr'),
            preserve_default=False,
        ),
    ]
