# Generated by Django 4.2.5 on 2023-11-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
